### ISSUE TITLE
Can "remote" support mutiple proxy-domain

### ISSUE THREAD

**Issue by switer** [vibegui/remote#8]
Can "remote" support mutiple proxy-domain, just like:

``` json
"proxy": {
        "hosts": ["localhost:9000", "other-domain.com", "other-domain2.com"]
 },
```

**Comment by vibegui** [comment]
Unfortunately, no :(

I'm actually looking into making remote into a connect middleware. Maybe I'll join efforts with grunt-connect-proxy. IDK.
